/* ═══════════════════════════════════════
   VISARI STUDIO — app.js
   ═══════════════════════════════════════ */

const $=id=>document.getElementById(id);
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1400)}
function copyText(t){navigator.clipboard.writeText(t.trim()).then(()=>toast('Copied'))}

// ── Nav ──
function go(id){document.querySelectorAll('.sec').forEach(s=>s.classList.remove('on'));document.querySelectorAll('.nl[data-s]').forEach(l=>l.classList.remove('on'));$('sec-'+id).classList.add('on');document.querySelector('[data-s="'+id+'"]').classList.add('on');closeM();window.scrollTo(0,0)}
function toggleM(){$('sidebar').classList.toggle('open');$('ov').classList.toggle('show')}
function closeM(){$('sidebar').classList.remove('open');$('ov').classList.remove('show')}

// ── Theme ──
function toggleTheme(){var d=document.documentElement,dk=d.getAttribute('data-theme')==='dark';d.setAttribute('data-theme',dk?'light':'dark');$('tl').textContent=dk?'Light':'Dark';$('sw').classList.toggle('on',dk);drawEasing&&drawEasing();localStorage.setItem('vs-t',dk?'light':'dark')}
(function(){var s=localStorage.getItem('vs-t');if(s==='light'){document.documentElement.setAttribute('data-theme','light');$('tl').textContent='Light';$('sw').classList.add('on')}})();

// ── Colour utils ──
function h2hsl(h){var r=parseInt(h.slice(1,3),16)/255,g=parseInt(h.slice(3,5),16)/255,b=parseInt(h.slice(5,7),16)/255;var mx=Math.max(r,g,b),mn=Math.min(r,g,b);var hh,s,l=(mx+mn)/2;if(mx===mn)hh=s=0;else{var d=mx-mn;s=l>.5?d/(2-mx-mn):d/(mx+mn);switch(mx){case r:hh=((g-b)/d+(g<b?6:0))/6;break;case g:hh=((b-r)/d+2)/6;break;case b:hh=((r-g)/d+4)/6;break}}return[Math.round(hh*360),Math.round(s*100),Math.round(l*100)]}
function hsl2h(h,s,l){h=((h%360)+360)%360;s/=100;l/=100;var a=s*Math.min(l,1-l);var f=function(n){var k=(n+h/30)%12;var c=l-a*Math.max(Math.min(k-3,9-k,1),-1);return Math.round(255*c).toString(16).padStart(2,'0')};return'#'+f(0)+f(8)+f(4)}
function h2rgb(h){return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)]}
function lum(r,g,b){var a=[r,g,b].map(function(v){v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)});return .2126*a[0]+.7152*a[1]+.0722*a[2]}
function cRat(h1,h2){var c1=h2rgb(h1),c2=h2rgb(h2);var l1=lum(c1[0],c1[1],c1[2]),l2=lum(c2[0],c2[1],c2[2]);return(Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)}

// ── Palette ──
var harm='complement';
function setH(t){harm=t;updPal()}
function genHarm(hex,type){var hs=h2hsl(hex),h=hs[0],s=hs[1],l=hs[2];var c=[hex];switch(type){case'complement':c.push(hsl2h(h+180,s,l),hsl2h(h,Math.max(s-20,10),Math.min(l+30,90)),hsl2h(h+180,Math.max(s-20,10),Math.min(l+30,90)),hsl2h(h,s,Math.max(l-25,10)));break;case'analogous':c.push(hsl2h(h-30,s,l),hsl2h(h+30,s,l),hsl2h(h-15,Math.max(s-15,10),Math.min(l+20,90)),hsl2h(h+15,Math.max(s-15,10),Math.min(l+20,90)));break;case'triadic':c.push(hsl2h(h+120,s,l),hsl2h(h+240,s,l),hsl2h(h,Math.max(s-25,10),Math.min(l+25,90)),hsl2h(h+120,Math.max(s-25,10),Math.min(l+25,90)));break;case'split':c.push(hsl2h(h+150,s,l),hsl2h(h+210,s,l),hsl2h(h,s,Math.min(l+30,90)),hsl2h(h+180,s,Math.max(l-20,10)));break;case'tetradic':c.push(hsl2h(h+90,s,l),hsl2h(h+180,s,l),hsl2h(h+270,s,l));break}return c}
function updPal(){var hex=$('bCol').value;$('bHex').value=hex;var c=genHarm(hex,harm);$('palStrip').innerHTML=c.map(function(x){return'<div class="sw" style="background:'+x+'" onclick="copyText(\''+x+'\')"><span class="sw-l">'+x+'</span></div>'}).join('');$('palCss').innerHTML='<div class="code-l">CSS Variables</div><div class="code" onclick="copyText(this.textContent)">:root {\n'+c.map(function(x,i){return'  --colour-'+(i+1)+': '+x+';'}).join('\n')+'\n}</div>'}
var starters=[{n:'Midnight',c:['#0f0f23','#1a1a3e','#4a4a8a','#8888cc','#ccccff']},{n:'Forest',c:['#1a2e1a','#2d5a2d','#4a8c4a','#7bc47b','#c8f0c8']},{n:'Ember',c:['#2d1b0e','#8b4513','#d2691e','#f4a460','#ffe4c4']},{n:'Ocean',c:['#0a1628','#1e3a5f','#3a7bd5','#63b3ed','#bee3f8']},{n:'Plum',c:['#1a0a1a','#4a154b','#7c3085','#b660cd','#e8b4f8']},{n:'Slate',c:['#0f1419','#1e2630','#384250','#6b7b8d','#b0bec5']}];
function ldStarters(){$('starters').innerHTML=starters.map(function(p){return'<div class="card" style="cursor:pointer;padding:10px" onclick="document.getElementById(\'bCol\').value=\''+p.c[2]+'\';document.getElementById(\'bHex\').value=\''+p.c[2]+'\';updPal()"><div style="display:flex;overflow:hidden;margin-bottom:6px">'+p.c.map(function(c){return'<div style="flex:1;height:28px;background:'+c+'"></div>'}).join('')+'</div><div style="font-size:11px;font-weight:600">'+p.n+'</div></div>'}).join('')}

// ── Tints ──
var tints=[{hex:'#6366f1',sat:0}];
var T_LABELS=['0','50','100','200','300','400','500','600','700','800','900','950','1000'];
var T_LIGHT=[100,97,93,85,75,62,50,38,28,18,10,6,0];
function genTintScale(cfg){var hs=h2hsl(cfg.hex),h=hs[0],s=hs[1];var sat=Math.max(0,Math.min(100,s+cfg.sat));return T_LIGHT.map(function(l){return hsl2h(h,l===100||l===0?0:sat,l)})}
function renderTints(){$('tintContainer').innerHTML=tints.map(function(cfg,idx){var scale=genTintScale(cfg);return'<div class="tint-row"><div class="row mb"><input type="color" value="'+cfg.hex+'" style="width:28px;height:24px" onchange="tints['+idx+'].hex=this.value;renderTints()"><input type="text" value="'+cfg.hex+'" style="width:76px;font-family:var(--mono);font-size:10px" onchange="tints['+idx+'].hex=this.value;renderTints()"><label style="font-size:9px;color:var(--t2);margin-left:8px">Saturation</label><input type="range" min="-30" max="30" value="'+cfg.sat+'" style="width:120px" oninput="tints['+idx+'].sat=+this.value;renderTints()"><span style="font-family:var(--mono);font-size:9px;color:var(--t2);min-width:28px">'+(cfg.sat>0?'+':'')+cfg.sat+'</span>'+(idx>0?'<button class="btn btn-s" onclick="tints.splice('+idx+',1);renderTints()">Remove</button>':'')+'</div><div style="display:grid;grid-template-columns:repeat(13,1fr);gap:2px;margin-bottom:4px">'+scale.map(function(c,i){return'<div class="tint-cell" style="background:'+c+'" onclick="copyText(\''+c+'\')"><div class="tip">'+T_LABELS[i]+': '+c+'</div></div>'}).join('')+'</div><div style="display:grid;grid-template-columns:repeat(13,1fr);gap:2px">'+T_LABELS.map(function(l){return'<span style="font-size:7px;font-family:var(--mono);color:var(--t3);text-align:center">'+l+'</span>'}).join('')+'</div></div>'}).join('');var css=':root {\n';tints.forEach(function(cfg,idx){var scale=genTintScale(cfg);var nm='colour-'+(idx+1);scale.forEach(function(c,i){css+='  --'+nm+'-'+T_LABELS[i]+': '+c+';\n'})});css+='}';$('tintCssOut').innerHTML='<div class="code-l">CSS Variables</div><div class="code" onclick="copyText(this.textContent)">'+css+'</div>'}
function addTint(){tints.push({hex:hsl2h(Math.floor(Math.random()*360),65,50),sat:0});renderTints()}

// ── Gradients ──
var gPre=[{n:'Indigo Rose',css:'linear-gradient(135deg,#667eea,#764ba2)'},{n:'Peach',css:'linear-gradient(to right,#ee9ca7,#ffdde1)'},{n:'Aqua',css:'linear-gradient(to right,#1a2980,#26d0ce)'},{n:'Celestial',css:'linear-gradient(to right,#c33764,#1d2671)'},{n:'Relay',css:'linear-gradient(to right,#3a1c71,#d76d77,#ffaf7b)'},{n:'Sublime',css:'linear-gradient(to right,#fc5c7d,#6a82fb)'},{n:'Flare',css:'linear-gradient(to right,#f12711,#f5af19)'},{n:'Moonlit',css:'linear-gradient(to right,#0f2027,#203a43,#2c5364)'},{n:'Frost',css:'linear-gradient(to right,#000428,#004e92)'},{n:'Emerald',css:'linear-gradient(to right,#348f50,#56b4d3)'},{n:'Velvet',css:'linear-gradient(to right,#da4453,#89216b)'}];
function updG(){var c1=$('g1').value,c2=$('g2').value,d=$('gD').value,css='linear-gradient('+d+', '+c1+', '+c2+')';$('gP').style.background=css;$('gC').textContent='background: '+css+';'}
function ldGrad(){$('gPresets').innerHTML=gPre.map(function(g){return'<div class="grad-p" style="background:'+g.css+'" onclick="copyText(\'background: '+g.css+';\')" ><div class="tip">'+g.n+'</div></div>'}).join('')}

// ── Contrast ──
function chkC(){var fg=$('cF').value,bg=$('cB').value;$('cFh').value=fg;$('cBh').value=bg;$('cPrev').style.background=bg;$('cPrev').style.color=fg;$('cS1').style.color=fg;$('cS2').style.color=fg;var r=cRat(fg,bg),v=r.toFixed(2),aaN=r>=4.5,aaL=r>=3,aaaN=r>=7,aaaL=r>=4.5;$('cRes').innerHTML='<div class="card" style="text-align:center"><div class="cr-val">'+v+':1</div><div style="font-size:10px;color:var(--t2);margin-top:2px">Contrast Ratio</div></div><div class="card"><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><div><div style="font-size:9px;color:var(--t2);margin-bottom:2px">AA Normal</div><span class="tag '+(aaN?'tag-pass':'tag-fail')+'">'+(aaN?'PASS':'FAIL')+'</span></div><div><div style="font-size:9px;color:var(--t2);margin-bottom:2px">AA Large</div><span class="tag '+(aaL?'tag-pass':'tag-fail')+'">'+(aaL?'PASS':'FAIL')+'</span></div><div><div style="font-size:9px;color:var(--t2);margin-bottom:2px">AAA Normal</div><span class="tag '+(aaaN?'tag-pass':'tag-fail')+'">'+(aaaN?'PASS':'FAIL')+'</span></div><div><div style="font-size:9px;color:var(--t2);margin-bottom:2px">AAA Large</div><span class="tag '+(aaaL?'tag-pass':'tag-fail')+'">'+(aaaL?'PASS':'FAIL')+'</span></div></div></div>'}
function swC(){var f=$('cF').value,b=$('cB').value;$('cF').value=b;$('cB').value=f;chkC()}

// ── Type Scale ──
function genTS(){var base=parseFloat($('tsB').value),ratio=parseFloat($('tsR').value);var nms=['xs','sm','base','lg','xl','2xl','3xl','4xl','5xl'],exps=[-2,-1,0,1,2,3,4,5,6];var css=':root {\n';$('tsOut').innerHTML=exps.map(function(e,i){var s=(base*Math.pow(ratio,e)).toFixed(1);css+='  --text-'+nms[i]+': '+s+'px;\n';return'<div class="ts-row"><div class="ts-meta">'+nms[i]+'<br>'+s+'px</div><div style="flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:'+s+'px;font-weight:'+(e>=3?600:400)+'">The quick brown fox</div></div>'}).reverse().join('');css+='}';$('tsCss').innerHTML='<div class="code-l">CSS Variables</div><div class="code" onclick="copyText(this.textContent)">'+css+'</div>'}

// ── Font Matcher ──
var fontDB={
  'Playfair Display':{w:700,cat:'serif',pairs:['Source Sans 3','DM Sans','Instrument Sans','Commissioner']},
  'Sora':{w:700,cat:'sans',pairs:['DM Sans','Inter Tight','Commissioner','Source Sans 3']},
  'Fraunces':{w:700,cat:'serif',pairs:['Commissioner','Instrument Sans','Inter Tight','Source Sans 3']},
  'Bricolage Grotesque':{w:700,cat:'sans',pairs:['Inter Tight','Source Sans 3','Commissioner','DM Sans']},
  'Outfit':{w:700,cat:'sans',pairs:['DM Sans','Source Sans 3','Commissioner','Instrument Sans']},
  'Manrope':{w:700,cat:'sans',pairs:['Inter Tight','Source Sans 3','DM Sans','Commissioner']},
  'Instrument Sans':{w:700,cat:'sans',pairs:['Source Sans 3','Commissioner','Inter Tight','DM Sans']},
};
function updateFontMatch(){var heading=$('fpSelect').value;var db=fontDB[heading];if(!db)return;$('fpG').innerHTML=db.pairs.map(function(body){var imp=heading.replace(/ /g,'+')+':wght@'+db.w+'&family='+body.replace(/ /g,'+')+':wght@400;500';var url='https://fonts.googleapis.com/css2?family='+imp+'&display=swap';return'<div class="card fp" onclick="copyText(\''+url+'\')"><div class="fp-h" style="font-family:\''+heading+'\','+db.cat+';font-weight:'+db.w+';font-size:24px">The quick brown fox</div><div class="fp-b" style="font-family:\''+body+'\',sans-serif">Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump.</div><div class="fp-m">'+heading+' + '+body+' · Click to copy import</div></div>'}).join('')}

// ── Buttons ──
function ldBtns(){var b=[
  {n:'Primary Solid',css:'padding:12px 28px;background:#f5f5f5;color:#0a0a0a;border:none;font-size:14px;font-weight:600'},
  {n:'Outline',css:'padding:12px 28px;background:transparent;color:var(--t0);border:1.5px solid var(--border-h);font-size:14px;font-weight:500'},
  {n:'Ghost',css:'padding:12px 28px;background:transparent;color:var(--t1);border:none;font-size:14px;font-weight:500'},
  {n:'Pill',css:'padding:10px 24px;background:var(--bg-2);color:var(--t0);border:1px solid var(--border);border-radius:999px;font-size:13px;font-weight:500'},
  {n:'Underline',css:'padding:4px 0;background:transparent;color:var(--t0);border:none;border-bottom:1.5px solid var(--t0);font-size:14px;font-weight:500'},
  {n:'Small Tag',css:'padding:5px 14px;background:var(--bg-2);color:var(--t1);border:1px solid var(--border);font-size:11px;font-weight:500'},
  {n:'Large CTA',css:'padding:16px 40px;background:var(--t0);color:var(--bg-0);border:none;font-size:16px;font-weight:700;letter-spacing:-0.01em'},
  {n:'Glass',css:'padding:12px 28px;background:rgba(255,255,255,0.06);color:#fff;border:1px solid rgba(255,255,255,0.1);font-size:14px;font-weight:500;backdrop-filter:blur(12px)'},
];
$('btnG').innerHTML=b.map(function(x){return'<div class="btn-cell"><button style="'+x.css+';cursor:pointer;font-family:var(--font);outline:none">Button</button><span class="bn">'+x.n+'</span><div class="code" style="font-size:9px;width:100%;margin-top:6px;white-space:pre-wrap" onclick="event.stopPropagation();copyText(this.textContent)">'+x.css+'</div></div>'}).join('')}

// ── Layouts ──
function ldLay(){var l=[
  {n:'Hero — Centred',d:'Full-width, centred text stack.',css:'.hero {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  text-align: center;\n  padding: 80px 24px;\n}\n.hero-content { max-width: 720px; }',p:'<div style="display:flex;flex-direction:column;align-items:center;gap:6px;padding:16px"><div class="lph" style="width:55%;height:14px"></div><div class="lph" style="width:75%;height:8px"></div><div class="lph" style="width:35%;height:24px;margin-top:3px"></div></div>'},
  {n:'Hero — Split',d:'50/50 text + image.',css:'.split {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 40px;\n  align-items: center;\n}\n@media (max-width: 810px) {\n  .split { grid-template-columns: 1fr; }\n}',p:'<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:10px"><div style="display:flex;flex-direction:column;gap:5px;justify-content:center"><div class="lph" style="height:12px;width:75%"></div><div class="lph" style="height:7px;width:100%"></div></div><div class="lph" style="height:70px"></div></div>'},
  {n:'Feature Grid (3-col)',d:'Auto-wrapping grid.',css:'.features {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 24px;\n}',p:'<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px;padding:8px"><div class="lph" style="height:50px"></div><div class="lph" style="height:50px"></div><div class="lph" style="height:50px"></div></div>'},
  {n:'CTA Banner',d:'Full-width centred band.',css:'.cta {\n  padding: 48px 24px;\n  text-align: center;\n}',p:'<div style="background:var(--bg-3);padding:14px;text-align:center"><div class="lph" style="height:10px;width:45%;margin:0 auto 6px"></div><div class="lph" style="height:20px;width:25%;margin:0 auto"></div></div>'},
  {n:'Testimonials',d:'3-col card row.',css:'.testimonials {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 16px;\n}',p:'<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:5px;padding:8px"><div class="lph" style="height:44px"></div><div class="lph" style="height:44px"></div><div class="lph" style="height:44px"></div></div>'},
  {n:'Footer — 4 Column',d:'Logo + 3 link columns.',css:'.footer {\n  display: grid;\n  grid-template-columns: 2fr 1fr 1fr 1fr;\n  gap: 32px;\n}',p:'<div style="display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:5px;padding:8px"><div class="lph" style="height:36px"></div><div class="lph" style="height:36px"></div><div class="lph" style="height:36px"></div><div class="lph" style="height:36px"></div></div>'},
];
$('layG').innerHTML=l.map(function(x){return'<div class="card" style="padding:12px"><div class="lp">'+x.p+'</div><div style="font-size:12px;font-weight:600;margin:8px 0 2px">'+x.n+'</div><p class="d" style="margin-bottom:5px">'+x.d+'</p><div class="code" style="font-size:10px" onclick="copyText(this.textContent)">'+x.css+'</div></div>'}).join('')}

// ── Icons ──
var activeCat='all';
function ldIcons(){var catCounts={};icons.forEach(function(i){catCounts[i.c]=(catCounts[i.c]||0)+1});$('iCats').innerHTML='<button class="pt-t on" onclick="setCat(\'all\',this)">All ('+icons.length+')</button>'+Object.entries(CATS).map(function(e){return catCounts[e[0]]?'<button class="pt-t" onclick="setCat(\''+e[0]+'\',this)">'+e[1]+' ('+catCounts[e[0]]+')</button>':''}).join('');renderIcons()}
function renderIcons(){var q=($('iSrch').value||'').toLowerCase();var filtered=icons.filter(function(i){var catMatch=activeCat==='all'||i.c===activeCat;var searchMatch=!q||i.n.indexOf(q)!==-1||i.c.indexOf(q)!==-1||(CATS[i.c]||'').toLowerCase().indexOf(q)!==-1||(PACKS[i.p]||'').toLowerCase().indexOf(q)!==-1;return catMatch&&searchMatch});$('iG').innerHTML=filtered.map(function(i){var isFill=i.p==='S';var svg=isFill?'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="'+i.d+'"/></svg>':'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="'+i.d+'"/></svg>';var escapedSvg=svg.replace(/'/g,"\\'").replace(/"/g,'&quot;');return'<div class="ic" data-n="'+i.n+'" data-c="'+i.c+'" onclick="copyText(\''+escapedSvg+'\')"><svg viewBox="0 0 24 24" '+(isFill?'fill="currentColor" stroke="none"':'')+'><path d="'+i.d+'"/></svg><span>'+i.n+'</span><span style="font-size:6px;color:var(--t3);margin-top:-2px">'+PACKS[i.p]+'</span></div>'}).join('');$('iCount').textContent=filtered.length}
function setCat(cat,el){activeCat=cat;document.querySelectorAll('#iCats .pt-t').forEach(function(b){b.classList.remove('on')});el.classList.add('on');renderIcons()}
function fltI(){renderIcons()}

// ── Image Converter ──
var imgFiles=[],imgOriginals=[];
var _imgTimer=null;
function debouncedImgPreview(){clearTimeout(_imgTimer);_imgTimer=setTimeout(updateImgPreview,150)}
function handleImgFiles(files){imgFiles=[];imgOriginals=[];for(var i=0;i<files.length;i++){if(files[i].type.startsWith('image/'))imgFiles.push(files[i])}if(!imgFiles.length)return;$('imgControls').style.display='block';$('imgResults').style.display='block';var loaded=0;imgOriginals=new Array(imgFiles.length);imgFiles.forEach(function(file,idx){var reader=new FileReader();reader.onload=function(e){var img=new Image();img.onload=function(){imgOriginals[idx]={img:img,name:file.name,size:file.size,w:img.width,h:img.height};loaded++;if(loaded===imgFiles.length)updateImgPreview()};img.src=e.target.result};reader.readAsDataURL(file)})}
function updateImgPreview(){var format=$('imgFormat').value;var quality=parseInt($('imgQuality').value)/100;var maxW=parseInt($('imgMaxWidth').value)||0;var ext={'image/webp':'webp','image/png':'png','image/jpeg':'jpg','image/avif':'avif'}[format]||'webp';var list=$('imgList');list.innerHTML='';imgOriginals.forEach(function(orig,idx){if(!orig)return;var canvas=document.createElement('canvas');var ctx=canvas.getContext('2d');var w=orig.w,h=orig.h;if(maxW>0&&w>maxW){h=Math.round(h*(maxW/w));w=maxW}canvas.width=w;canvas.height=h;if(format==='image/jpeg'){ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h)}ctx.drawImage(orig.img,0,0,w,h);var dataUrl;try{dataUrl=canvas.toDataURL(format,quality)}catch(e){dataUrl=canvas.toDataURL('image/png')}var cs=Math.round((dataUrl.length-dataUrl.indexOf(',')-1)*0.75);var sv=orig.size>0?Math.round((1-cs/orig.size)*100):0;var sc=sv>0?'color:#16a34a':'color:#dc2626';var bn=orig.name.replace(/\.[^.]+$/,'');var card=document.createElement('div');card.className='card';card.style.padding='10px';card.innerHTML='<div style="background:var(--bg-2);margin-bottom:8px;overflow:hidden"><img src="'+dataUrl+'" style="width:100%;display:block;max-height:160px;object-fit:contain"></div><div style="font-size:11px;font-weight:600;margin-bottom:4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+bn+'.'+ext+'</div><div style="font-size:10px;color:var(--t2);margin-bottom:2px">'+w+' × '+h+'px</div><div style="font-size:10px;color:var(--t2)">'+formatBytes(orig.size)+' → '+formatBytes(cs)+' <span style="'+sc+';font-weight:600">'+(sv>0?'−':'+')+Math.abs(sv)+'%</span></div><button class="btn btn-s" style="margin-top:8px;width:100%" onclick="downloadImg('+idx+')">Download</button>';list.appendChild(card)})}
function formatBytes(b){if(b<1024)return b+' B';if(b<1048576)return(b/1024).toFixed(1)+' KB';return(b/1048576).toFixed(1)+' MB'}
function downloadImg(idx){var orig=imgOriginals[idx];if(!orig)return;var format=$('imgFormat').value;var quality=parseInt($('imgQuality').value)/100;var maxW=parseInt($('imgMaxWidth').value)||0;var ext={'image/webp':'webp','image/png':'png','image/jpeg':'jpg','image/avif':'avif'}[format]||'webp';var canvas=document.createElement('canvas');var ctx=canvas.getContext('2d');var w=orig.w,h=orig.h;if(maxW>0&&w>maxW){h=Math.round(h*(maxW/w));w=maxW}canvas.width=w;canvas.height=h;if(format==='image/jpeg'){ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h)}ctx.drawImage(orig.img,0,0,w,h);canvas.toBlob(function(blob){if(!blob){toast('Format not supported');return}var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=orig.name.replace(/\.[^.]+$/,'')+'.'+ext;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(a.href);toast('Downloaded '+a.download)},format,quality)}
function convertAllImages(){imgOriginals.forEach(function(_,idx){setTimeout(function(){downloadImg(idx)},idx*200)})}
function clearImages(){imgFiles=[];imgOriginals=[];$('imgControls').style.display='none';$('imgResults').style.display='none';$('imgList').innerHTML='';$('imgFileInput').value=''}

// ── Prompt Library (localStorage) ──
function getPrompts(){try{return JSON.parse(localStorage.getItem('vs-prompts')||'[]')}catch(e){return[]}}
function setPrompts(p){localStorage.setItem('vs-prompts',JSON.stringify(p))}
function savePrompt(){var text=$('promptText').value.trim();if(!text){toast('Enter a prompt first');return}var tags=$('promptTags').value.trim();var fileInput=$('promptImg');var prompt={id:Date.now(),text:text,tags:tags,img:'',date:new Date().toLocaleDateString('en-AU')};if(fileInput.files&&fileInput.files[0]){var reader=new FileReader();reader.onload=function(e){prompt.img=e.target.result;var prompts=getPrompts();prompts.unshift(prompt);setPrompts(prompts);$('promptText').value='';$('promptTags').value='';fileInput.value='';renderPrompts();toast('Prompt saved')};reader.readAsDataURL(fileInput.files[0])}else{var prompts=getPrompts();prompts.unshift(prompt);setPrompts(prompts);$('promptText').value='';$('promptTags').value='';renderPrompts();toast('Prompt saved')}}
function renderPrompts(){var prompts=getPrompts();var q=($('promptSearch').value||'').toLowerCase();var filtered=prompts.filter(function(p){return!q||p.text.toLowerCase().indexOf(q)!==-1||(p.tags||'').toLowerCase().indexOf(q)!==-1});$('promptEmpty').style.display=filtered.length?'none':'block';$('promptGrid').innerHTML=filtered.map(function(p){return'<div class="prompt-card">'+(p.img?'<img src="'+p.img+'" alt="Output">':'<div style="width:100%;height:80px;background:var(--bg-2);display:flex;align-items:center;justify-content:center;margin-bottom:12px;font-size:10px;color:var(--t2)">No image</div>')+'<div class="prompt-text" onclick="copyText(this.textContent)">'+p.text.replace(/</g,'&lt;')+'</div><div style="display:flex;justify-content:space-between;align-items:center"><div class="prompt-meta">'+(p.tags?p.tags+' · ':'')+p.date+'</div><button class="btn btn-s" onclick="deletePrompt('+p.id+')">Delete</button></div></div>'}).join('')}
function deletePrompt(id){var prompts=getPrompts().filter(function(p){return p.id!==id});setPrompts(prompts);renderPrompts();toast('Deleted')}

// ── Init ──
document.addEventListener('DOMContentLoaded',function(){
  updPal();ldStarters();renderTints();updG();ldGrad();chkC();
  genTS();updateFontMatch();
  ldBtns();ldLay();ldIcons();
  renderPrompts();
});
